---
title: "Style Example"
author: "@hrbrmstr"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Style Example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r echo=FALSE, results="asis"}
cat("<style>
.tweet-wrap { width: 564px; vertical-align: top; border: 1px solid #b2b2b2 !important; padding: 6pt; border-radius: 5px !important; margin-bottom: 4pt; }
div.tweet-avatar-img-crop { width: 48px; height: 48px; position: relative; overflow: hidden; border-radius: 50% !important; }
td.tweet-avatar { padding-top: 16px }
.tweet-div { font-family: 'Helvetica Neue', sans-serif; font-weight: 300; font-size: 1em; line-height: 1.3em; border: 0.5px solid rgba(27, 40, 54, 0.5); border-radius: 5px; width: 494px; display: block; padding: 12px 6px 12px 6px; margin-bottom: 4pt; }
a.tweet-lnk { font-size: 0.85em; line-height: 1.3em; text-decoration: none; color:rgb(29, 161, 242) }
img.tweet-img { display: YYY; max-width:100%; border: 0.25px dotted black; margin-top:12px; }
span.tweet-hashtag { color:rgb(29, 161, 242) }
div.tweet-intro { margin-bottom:6px }
span.tweet-mention { color:rgb(29, 161, 242) }
span.tweet-source { font-size: 1.1em; font-weight: 700 }
span.tweet-ts { font-size: 0.75em; line-height: 1.3em; color=#2b2b2b }
</style>
")
```
```{r setup2, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, message=FALSE, warning=FALSE)
```

```{r libs}
library(rtweet)
library(tweetview)
library(tidyverse)
```

```{r data, cache=TRUE}
lego <- lookup_statuses("952295018143690752")
```

```{r l1, results='asis'}
cat(style_tweet(lego, print = FALSE, css=""))
```

```{r, results='asis'}
cat(style_tweet(lego, print = FALSE, css=""))
```

```{r l2, results='asis'}
cat(style_tweet(lego, avatar = TRUE, print=FALSE, css=""))
```